version: '3'

services:

  php:
    container_name: ${PREFIX}_php
    image: ${PREFIX}_php
    build: ./php
    logging:
       driver: "json-file"
       options:
           max-size: "200k"
           max-file: "10"

  fpm:
    container_name: ${PREFIX}_fpm
    image: ${PREFIX}_fpm
    build: ./fpm
    depends_on:
      - php
    restart: always
    expose:
      - 9000
    volumes:
      - ${SOURCE_DIR}:${TARGET_DIR}
      - ./logs/php-fpm:/var/log/php-fpm 
    logging:
       driver: "json-file"
       options:
           max-size: "200k"
           max-file: "10"

  composer:
    container_name: ${PREFIX}_composer
    image: ${PREFIX}_composer
    build: ./composer
    depends_on:
      - php
    restart: always
    volumes:
      - ${SOURCE_DIR}:${TARGET_DIR}
    stdin_open: true
    tty: true
    logging:
       driver: "json-file"
       options:
           max-size: "200k"
           max-file: "10"

  nginx:
    container_name: ${PREFIX}_nginx
    image: ${PREFIX}_nginx
    build: ./nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ${SOURCE_DIR}:${TARGET_DIR}
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./logs/nginx:/var/log/nginx

    links:
      - fpm
    stdin_open: true
    tty: true
    logging:
       driver: "json-file"
       options:
           max-size: "200k"
           max-file: "10"

  mysql:
    image: mysql:5.7
    container_name: ${PREFIX}_mysql
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./mysql/data/:/var/lib/mysql
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    logging:
       driver: "json-file"
       options:
           max-size: "200k"
           max-file: "10"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ${PREFIX}_phpmyadmin

    restart: always
    links:
     - mysql
    ports:
      - 8080:80
    environment:
       MYSQL_USERNAME: root
       MYSQL_ROOT_PASSWORD:  ${MYSQL_ROOT_PASSWORD}
       PMA_HOST: mysql
       PMA_ARBITRARY: 1
    logging:
       driver: "json-file"
       options:
           max-size: "200k"
           max-file: "10"

